---
services:
  terraform:
    image: hashicorp/terraform:1.15.8@sha256:7ae513256f7ce67879e218ae8593d6fbe216ec9e123abe6c94e4e10704857963
    container_name: terraform
    user: "1000:1000"
    environment:
      - TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}
    volumes:
      - ./:/terraform
    working_dir: /terraform
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
