---
services:
  terraform:
    image: hashicorp/terraform:1.16.5@sha256:c7926feace05d0f7e73542842bf3945924e955a1f782cf000ccbb8d18fa42d77
    container_name: terraform
    user: "1000:1000"
    environment:
      - TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}
    volumes:
      - ./:/terraform
    working_dir: /terraform
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
