---
services:
  terraform:
    image: hashicorp/terraform:1.15.7@sha256:40e61a86763083ea987ded0ffa15f6d75e0df48ed16275811f949b3ecbcd8aae
    container_name: terraform
    user: "1000:1000"
    environment:
      - TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}
    volumes:
      - ./:/terraform
    working_dir: /terraform
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
